/**
 * GENERATED by scripts/seo/wiki-entities.ts — do not edit by hand.
 * Wikipedia-derived entity variants (canonical titles, lead-section bold
 * synonyms, and What-links-here redirects) per location key.
 * Keys: "county:<countySlug>" and "<countySlug>/<townSlug>".
 */

export const wikiVariants: Record<string, readonly string[]> = {
    "county:greater-manchester": [
        "Greater Manchester, England",
        "Greater Manchester City Region"
    ],
    "county:lancashire": [
        "Lancashire, England",
        "Lancashire Administration County",
        "Lancashire County Palatine"
    ],
    "county:merseyside": [
        "Merseyside, England"
    ],
    "county:cheshire": [
        "Cheshire, England",
        "County Palatine of Cheshire",
        "Cheshire, England, UK"
    ],
    "county:cumbria": [
        "Cumbria, England",
        "East Cumbria",
        "West Cumbria",
        "Cumbria County"
    ],
    "county:tyne-and-wear": [
        "Tyne and Wear, England",
        "Tyne and Wear County"
    ],
    "county:durham": [
        "Durham",
        "County Durham, England"
    ],
    "county:northumberland": [
        "County of Northumberland",
        "Northumberland, England"
    ],
    "county:teesside": [
        "Teesside urban area"
    ],
    "county:west-yorkshire": [
        "West Yorkshire, England"
    ],
    "county:south-yorkshire": [
        "South Yorkshire, England",
        "South Yorkshire County"
    ],
    "county:north-yorkshire": [
        "North Yorkshire, England"
    ],
    "county:east-riding-of-yorkshire": [
        "East Riding",
        "East Yorkshire",
        "East Riding of Yorkshire UA",
        "The East Riding of Yorkshire",
        "East Riding of Yorkshire, England"
    ],
    "county:derbyshire": [
        "Derbyshire, England",
        "Derbyshire, East Midlands"
    ],
    "county:nottinghamshire": [
        "Nottinghamshire, England",
        "Bracebridge, Nottinghamshire"
    ],
    "county:leicestershire": [
        "Leicestershire, England",
        "Leicestershire County Council County Hall"
    ],
    "county:lincolnshire": [
        "Lincolnshire, England",
        "County of Lincolnshire",
        "Central Lincolnshire",
        "Lincolnshire.gov.uk",
        "Greater Lincolnshire"
    ],
    "county:northamptonshire": [
        "Northants.",
        "Northamptonshire, England",
        "County of Northamptonshire"
    ],
    "county:rutland": [
        "Rutland UA",
        "Rutland, Great Britain",
        "Rutlandshire",
        "County of Rutland",
        "Rutland, England"
    ],
    "county:west-midlands": [],
    "county:staffordshire": [
        "Staffordshire, England"
    ],
    "county:warwickshire": [
        "Warks",
        "Warwickshire, England"
    ],
    "county:worcestershire": [
        "Worcs",
        "Worcestershire, England",
        "Worcestershire county"
    ],
    "county:shropshire": [
        "Salop",
        "Shropshire, England",
        "County of Shropshire"
    ],
    "county:herefordshire": [
        "English unitary district of county of Herefordshire",
        "County of Herefordshire",
        "Herefordshire, England"
    ],
    "county:essex": [
        "Upper",
        "Lower",
        "Essex, United Kingdom",
        "County of Essex",
        "Essex calf",
        "Essex, England",
        "Metropolitan Essex",
        "Greater Essex"
    ],
    "county:hertfordshire": [
        "Herts",
        "Hertfordshire, England",
        "Hertfordshire, UK",
        "County of Hertfordshire"
    ],
    "county:cambridgeshire": [
        "Clockwise from top",
        "Cambs.",
        "Cambridgeshire, England",
        "Cambridgeshire and Peterborough",
        "County of Cambridgeshire"
    ],
    "county:norfolk": [
        "Clockwise from top",
        "Norfolk, England",
        "Norfolkshire",
        "Norfolk, UK",
        "County of Norfolk",
        "Norfolk County, England"
    ],
    "county:suffolk": [
        "Suffolk, England",
        "County of Suffolk",
        "Suffolk, UK"
    ],
    "county:bedfordshire": [
        "Bedfordshire, England"
    ],
    "county:greater-london": [
        "London region",
        "Greater London, England",
        "Greater London Region",
        "Greater London administrative area",
        "Greater London county",
        "County of Greater London",
        "Greater London ceremonial country",
        "Ceremonial county of Greater London"
    ],
    "county:kent": [
        "County of Kent, England",
        "Kent, England",
        "Kent County, England",
        "County of Kent",
        "North West Kent",
        "County Kent",
        "Education in Kent",
        "Culture in Kent"
    ],
    "county:surrey": [
        "Surrey, England",
        "Kingdom of Surrey",
        "County of Surrey",
        "Historic buildings in Surrey"
    ],
    "county:east-sussex": [
        "East Sussex, England"
    ],
    "county:west-sussex": [
        "West Sussex, England",
        "West Sussex Youth Cabinet"
    ],
    "county:hampshire": [
        "Hants.",
        "County of Southampton",
        "Southamptonshire",
        "Hampshire, UK",
        "County of Hampshire",
        "Hampshire County Youth Orchestra",
        "Old Hampshire",
        "Hampshire, United Kingdom"
    ],
    "county:berkshire": [
        "Royal County of Berkshire",
        "Royal Berkshire",
        "Berkshire, England",
        "County of Berkshire",
        "Royal Country of Berkshire",
        "Berkshire, UK"
    ],
    "county:oxfordshire": [
        "Oxfordshire, England",
        "Oxfordshire, UK"
    ],
    "county:buckinghamshire": [
        "Buckinghamshire, England"
    ],
    "county:isle-of-wight": [
        "Isle of Wight UA",
        "Isle of Wight, England",
        "The Isle of Wight",
        "Isle of Wight marathon"
    ],
    "county:devon": [
        "Clockwise from top",
        "Devonshire",
        "Devon, England",
        "Devonshire, United Kingdom",
        "Devonshire Moors",
        "Culture of Devon",
        "Devon's culture",
        "Devon culture"
    ],
    "county:cornwall": [
        "Cornwall, England",
        "Cornwall, United Kingdom",
        "Languages of Cornwall",
        "Cornwall and Isles of Scilly",
        "Cornwallum",
        "Toponymy of Cornwall",
        "Ceremonial county of Cornwall",
        "East Cornwall"
    ],
    "county:somerset": [
        "Somersetshire",
        "Somerset, England",
        "County of Somerset",
        "Villages in Somerset",
        "Somersetshire, England",
        "Somersett"
    ],
    "county:dorset": [
        "Dorsetshire",
        "Dorset, England",
        "County of Dorset"
    ],
    "county:wiltshire": [
        "Wilts",
        "Wiltshire, England",
        "County of Wiltshire",
        "Wiltshire County"
    ],
    "county:gloucestershire": [
        "Glos.",
        "Gloucestershire, England",
        "Gloucestershire, United Kingdom",
        "County of Gloucestershire"
    ],
    "county:bristol": [
        "Bristol, England",
        "City of Bristol",
        "City of Bristol, United Kingdom",
        "Bristolshire",
        "Bristol, UK",
        "Bristol, United Kingdom",
        "The weather in Bristol",
        "County Borough of Bristol"
    ],
    "county:south-glamorgan": [
        "South Glamorgan, Wales"
    ],
    "county:west-glamorgan": [
        "West Glamorgan, Wales"
    ],
    "county:mid-glamorgan": [
        "Mid Glamorgan, Wales"
    ],
    "county:gwent": [],
    "county:dyfed": [
        "Dyfed, Wales",
        "County of Dyfed"
    ],
    "county:powys": [
        "Powys, Wales",
        "Powys County"
    ],
    "county:gwynedd": [
        "Gwynedd, Wales",
        "East Gwynedd",
        "West Gwynedd",
        "County of Gwynedd"
    ],
    "county:clwyd": [
        "Clwyd, Wales"
    ],
    "county:lothian": [
        "the Lothians",
        "Lothian Regional Council",
        "Lothians",
        "Lothian Region",
        "Edinburgh and Lothian"
    ],
    "county:strathclyde": [
        "Strathclyde Region",
        "Strathclyde Regional Council",
        "Region of Strathclyde"
    ],
    "county:grampian": [
        "Grampian region",
        "Grampian Regional Council"
    ],
    "county:tayside": [
        "Tayside Region",
        "Region of Tayside",
        "Tayside Regional Council"
    ],
    "county:fife": [
        "Kingdom of Fife",
        "Fife, Scotland",
        "Fife Region",
        "Fife County Council",
        "County of Fife",
        "North Fife",
        "Fife Regional Council",
        "Fifeshire"
    ],
    "county:central-scotland": [],
    "county:borders": [
        "The Mairches",
        "the Borders",
        "Scottish Borders Region",
        "Scottish Borders Council",
        "Scottish Borders council area",
        "The Scottish Borders"
    ],
    "county:dumfries-and-galloway": [
        "Dumfries and Galloway Council",
        "Dumfries and Galloway council area",
        "Dumfries and Galloway Regional Council"
    ],
    "county:highland": [
        "Highlands",
        "uplands",
        "Highland continent"
    ],
    "county:antrim": [
        "County Antrim, Ireland",
        "County Antrim, Northern Ireland"
    ],
    "county:down": [
        "County Down, Northern Ireland",
        "County Downpatrick",
        "Buskhill, County Down"
    ],
    "county:armagh": [
        "County Armagh, Northern Ireland"
    ],
    "county:tyrone": [
        "County Tyrone, Ireland"
    ],
    "county:fermanagh": [],
    "county:londonderry": [
        "Date",
        "County Derry"
    ],
    "greater-manchester/manchester": [
        "Manchester, England",
        "Manchester, UK",
        "Manchester, United Kingdom",
        "England Manchester",
        "Metropolitan Borough of Manchester",
        "City of Manchester",
        "Manchester developments",
        "County Borough of Manchester"
    ],
    "greater-manchester/salford": [
        "Salford, Manchester",
        "Salford, Lancashire",
        "Salford, Lancastershire",
        "Salford, England",
        "Salford, Greater Manchester",
        "Salfordian"
    ],
    "greater-manchester/stockport": [
        "Stockport, England",
        "Stockport, Greater Manchester"
    ],
    "greater-manchester/bolton": [
        "Bolton, Lancashire",
        "Bolton, England",
        "Bolton, Greater Manchester",
        "Bolton, Manchester",
        "Bolton, United Kingdom",
        "Albert Halls, Bolton"
    ],
    "greater-manchester/oldham": [
        "Oldham, England",
        "Oldham, Greater Manchester",
        "Oldham, Lancashire",
        "Oldham, United Kingdom",
        "Mumps, Oldham",
        "Oldham Mumps"
    ],
    "greater-manchester/rochdale": [
        "Rochdale, England",
        "Rochdale, Lancashire",
        "Rochdale, UK",
        "Rochdale, Greater Manchester"
    ],
    "greater-manchester/bury": [
        "Bury, Greater Manchester",
        "Bury, Lancashire",
        "Bury, GM",
        "Bury, Manchester",
        "Bury, Great Britain"
    ],
    "greater-manchester/wigan": [
        "Wigan, England",
        "Wigan, Greater Manchester",
        "Parish of Wigan",
        "Wigan, Lancashire",
        "Wigan, UK",
        "Wigan, Greater Manchester, England"
    ],
    "greater-manchester/sale": [
        "Sale, Greater Manchester",
        "Sale, Cheshire",
        "Sale, Lancashire",
        "Sale, England",
        "Sale, Manchester",
        "Sale, Trafford, Greater Manchester",
        "Sale Moor"
    ],
    "greater-manchester/stretford": [
        "Stretford Mall",
        "Stretford, Great Britain"
    ],
    "greater-manchester/leigh": [
        "Leigh, Greater Manchester",
        "Leigh, Lancashire"
    ],
    "greater-manchester/eccles": [
        "Eccles, Greater Manchester",
        "Municipal Borough of Eccles",
        "Eccles, Lancashire",
        "Eccles Borough Council",
        "Eccles, Manchester"
    ],
    "greater-manchester/hyde": [
        "Hyde, Greater Manchester",
        "Municipal Borough of Hyde",
        "Hyde, Cheshire",
        "St pauls school hyde"
    ],
    "greater-manchester/middleton": [
        "Middleton, Greater Manchester",
        "Middleton, Rochdale"
    ],
    "greater-manchester/denton": [
        "Denton, Greater Manchester",
        "Denton, Lancashire",
        "Denton, Tameside"
    ],
    "greater-manchester/heywood": [
        "Heywood, Greater Manchester",
        "Heywood, Lancashire",
        "Heywood, Rochdale"
    ],
    "greater-manchester/prestwich": [
        "Prestwich Borough Council",
        "Prestwich, Greater Manchester",
        "Prestwich, Lancashire"
    ],
    "greater-manchester/ashton-under-lyne": [
        "Ashton",
        "Ashton-under-Lyne, Lancashire",
        "Ashton-under-Lyne, Greater Manchester",
        "Ashton-under-Lyne Corporation"
    ],
    "greater-manchester/urmston": [
        "Urmston, Lancashire",
        "Urmston, Greater Manchester"
    ],
    "greater-manchester/stalybridge": [
        "Municipal Borough of Stalybridge",
        "Stalybridge Wakes",
        "Stalybridge, Cheshire",
        "Stalybridge, Tameside, Greater Manchester"
    ],
    "greater-manchester/farnworth": [
        "Farnworth, Lancashire",
        "Farnworth, Bolton",
        "Farnworth, Bolton, Greater Manchester"
    ],
    "greater-manchester/radcliffe": [
        "Radcliffe, Greater Manchester",
        "Radcliffe, Lancashire",
        "Radcliffe, Bury, Greater Manchester"
    ],
    "greater-manchester/horwich": [
        "Horwich Enterprise"
    ],
    "greater-manchester/altrincham": [
        "Altrincham, England",
        "Altrincham, Greater Manchester",
        "Altrincham, Cheshire"
    ],
    "lancashire/preston": [
        "Preston, Lancashire",
        "Preston Origins",
        "Prestonian",
        "Preston Guild",
        "The weather in Preston",
        "Preston Guild Merchant",
        "Preston, Lancashire, England",
        "Merchant guild of Preston"
    ],
    "lancashire/blackburn": [
        "Blackburn, Lancashire",
        "Blackburn, England",
        "County Borough of Blackburn",
        "Griffin Park Blackburn",
        "Blackburn Urban Area"
    ],
    "lancashire/blackpool": [
        "Blackpool, England",
        "Gay Blackpool",
        "Blackpool Sands, Blackpool",
        "Blackpool, Lancashire",
        "Devonshire, Blackpool",
        "Queestown, Blackpool",
        "Common Edge, Blackpool",
        "RAF Blackpool"
    ],
    "lancashire/lancaster": [
        "Lancaster, Lancashire",
        "Lancaster, England",
        "Lancaster Steiner School",
        "Municipal Borough of Lancaster",
        "Lancaster Municipal Borough",
        "Lancaster City Centre"
    ],
    "lancashire/burnley": [
        "Burnley, Lancashire",
        "Burnley, England",
        "County Borough of Burnley"
    ],
    "lancashire/chorley": [
        "Chorley, England",
        "Chorley Town Council",
        "Chorley, Lancashire",
        "Chorley Training College"
    ],
    "lancashire/accrington": [
        "Accrington, Lancashire"
    ],
    "lancashire/nelson": [
        "Nelson, Lancashire",
        "Nelson, England"
    ],
    "lancashire/colne": [
        "Colne, Lancashire"
    ],
    "lancashire/lytham-st-annes": [
        "Lytham St Annes, Lancashire"
    ],
    "lancashire/fleetwood": [
        "Fleetwood, England",
        "Fleetwood, Enlgand",
        "Fleetwood-on-Wyre",
        "Fleetwood, Lancashire"
    ],
    "lancashire/leyland": [
        "Leyland, Lancashire",
        "Leyland police station",
        "Leyland, England"
    ],
    "lancashire/morecambe": [
        "Morecambe, Lancashire"
    ],
    "lancashire/ormskirk": [
        "Ormskirk, Lancashire"
    ],
    "lancashire/skelmersdale": [
        "Skem",
        "Skelmersdale, England",
        "Skelmersdale, Lancashire"
    ],
    "merseyside/liverpool": [
        "Liverpool, England",
        "Liverpool, UK",
        "Liverpool, Britain",
        "Metropolitan Borough of Liverpool",
        "Liverpool, Merseyside",
        "County Borough of Liverpool",
        "Landmarks in Liverpool",
        "Liverpool, U.K."
    ],
    "merseyside/birkenhead": [
        "Birkenhead, Merseyside",
        "Birkenhead, England",
        "Birkenhead, United Kingdom",
        "Birkenhead County Borough Council",
        "County Borough of Birkenhead",
        "Birkenhead, Cheshire",
        "Birkenhead Corporation"
    ],
    "merseyside/st-helens": [
        "St Helens, Merseyside",
        "St Helens, Lancashire",
        "St Helens, St Helens",
        "County Borough of St Helens",
        "St Helens, Merseyside, England",
        "St Helens."
    ],
    "merseyside/southport": [
        "Southport, Lancashire",
        "Southport, England",
        "County Borough of Southport",
        "Southport, Merseyside"
    ],
    "cheshire/chester": [
        "Chester, Cheshire",
        "Chester, England",
        "County Borough of Chester",
        "Chester Urban Area"
    ],
    "cheshire/warrington": [
        "County Borough of Warrington",
        "Warrington Interchange",
        "Warrington, Lancashire",
        "Warrington, Cheshire",
        "Warrington, Warrington",
        "Warrington, England",
        "Warrington, United Kingdom"
    ],
    "cheshire/crewe": [
        "Crewe, England",
        "Crewe town centre",
        "Crewe, Cheshire"
    ],
    "cheshire/macclesfield": [
        "Macclesfield, Cheshire",
        "Macclesfield Built-up area"
    ],
    "cumbria/carlisle": [
        "Carlisle, England",
        "Carlisleshire",
        "Carlisle, Cumbria",
        "Carlisle, Cumberland",
        "Curse of Carlisle",
        "Her Majesty's Theatre, Carlisle",
        "Carlisle Art Gallery"
    ],
    "cumbria/barrow-in-furness": [
        "Barrow",
        "Barrow-in-Furness, Cumbria",
        "Barrow-in-Furness dialect",
        "County Borough of Barrow-in-Furness"
    ],
    "cumbria/kendal": [
        "Kirkby in Kendal",
        "Kirkby Kendal",
        "Kendal, England",
        "Municipal Borough of Kendal",
        "Kendal, Westmoreland",
        "Kirkby-Kendal",
        "Kirkby-in-Kendal",
        "Kendal, Cumbria"
    ],
    "cumbria/penrith": [
        "Penrith, Cumbria",
        "Penrith, England",
        "Penrith Urban District",
        "Penrith, Cumberland",
        "Castletown, Penrith",
        "Fair Hill, Penrith",
        "Penrith, United Kingdom",
        "Old Penrith"
    ],
    "cumbria/workington": [
        "Municipal Borough of Workington",
        "Workington, Cumbria"
    ],
    "cumbria/whitehaven": [
        "Whitehaven, England",
        "Whitehaven Urban District",
        "Whitehaven, Cumberland"
    ],
    "cumbria/keswick": [
        "Keswick, Cumbria",
        "Keswick, Cumberland",
        "Keswick Urban District"
    ],
    "cumbria/windermere": [
        "Winder Mere",
        "Windermere, England",
        "Lake Windermere",
        "Windermere, UK",
        "Windermere lake"
    ],
    "cumbria/ulverston": [
        "Ulverston, England",
        "Ulverstone, Lancashire",
        "Ulverston, Lancashire",
        "Ulverston, Cumbria"
    ],
    "cumbria/cockermouth": [
        "Cockermouth Urban District"
    ],
    "cumbria/ambleside": [
        "Ambleside Church of England Primary School"
    ],
    "tyne-and-wear/newcastle-upon-tyne": [
        "Newcastle",
        "City of Newcastle upon Tyne",
        "Metropolitan Borough of Newcastle upon Tyne",
        "Newcastle Upon Tyne, England",
        "Newcastle upon Tyne weather",
        "County Borough of Newcastle upon Tyne",
        "Newcastle upon Tyne, United Kingdom",
        "Newcastle upon Tyne, North East England"
    ],
    "tyne-and-wear/gateshead": [
        "Gateshead on Tyne",
        "Gateshead, England",
        "Gateshead, Tyne and Wear",
        "County Borough of Gateshead",
        "Gateshead-on-Tyne",
        "Gateshead, United Kingdom"
    ],
    "tyne-and-wear/sunderland": [
        "Sunderland, England",
        "Metropolitan Borough of Sunderland",
        "Sunderland, Tyne and Wear",
        "City of sunderland",
        "Greater Sunderland",
        "Sunderland, Co Durham",
        "Sunderland Town Council",
        "Sunderland, County Durham"
    ],
    "tyne-and-wear/south-shields": [
        "South Shields, England",
        "County Borough of South Shields",
        "Borough of South Shields",
        "South Shields RFC",
        "South Shields, Tyne and Wear",
        "South Shields, County Durham"
    ],
    "tyne-and-wear/tynemouth": [
        "Tynemouthshire",
        "Tynemouth, North Tyneside",
        "Tynemouth, Tyne and Wear",
        "County Borough of Tynemouth",
        "Tynemouth Pier",
        "Tynemouth North Pier lighthouse"
    ],
    "tyne-and-wear/whitley-bay": [],
    "tyne-and-wear/jarrow": [
        "Jarrow on Tyne",
        "Jarrow-on-Tyne",
        "Jarrow, Tyne and Wear",
        "Jarrow Slake",
        "Jarrow, South Tyneside"
    ],
    "tyne-and-wear/washington": [
        "Washington, Tyne and Wear",
        "Washington New Town",
        "Washington, County Durham",
        "Washington, Durham"
    ],
    "teesside/middlesbrough": [
        "Boro",
        "Middlesbrough, England",
        "Middlesbrough, Cleveland",
        "Middlesbrough, North Yorkshire",
        "Middlesbrough, Tees Valley",
        "Middlesbrough, Teesside",
        "Areas with in Middlesbrough",
        "Areas within Middlesbrough"
    ],
    "teesside/stockton-on-tees": [
        "Stockton-on-Tees UA",
        "Municipal Borough of Stockton-on-Tees",
        "Grangefield, Stockton-on-Tees",
        "Stockton-on-Tees, United Kingdom",
        "Stockton-on-Tees, Co Durham",
        "Stockton-on-Tees, England"
    ],
    "teesside/hartlepool": [
        "Hartlepool, England",
        "Hartlepools",
        "County Borough of Hartlepool"
    ],
    "teesside/redcar": [
        "Westfield, Redcar",
        "Redcar East",
        "Municipal Borough of Redcar",
        "Redcar, Yorkshire"
    ],
    "durham/durham": [
        "Durham, England",
        "Faith, foresight and industry.",
        "Durham, United Kingdom",
        "Durham, County Durham, England",
        "Durham, Durham",
        "Durham, County Durham",
        "Durham, UK"
    ],
    "durham/darlington": [
        "Darlington, England",
        "Urban changes in Darlington",
        "County Borough of Darlington",
        "Darlington, County Durham",
        "Darlington, Durham",
        "Darlington, Co Durham",
        "Darlington, United Kingdom",
        "Darlington, Tees Valley"
    ],
    "durham/bishop-auckland": [
        "Bishop Auckland, County Durham"
    ],
    "durham/chester-le-street": [
        "Chester-le-Street, County Durham"
    ],
    "durham/consett": [
        "Blackhill, Consett"
    ],
    "durham/peterlee": [
        "Peterlee, England",
        "Peterlee, County Durham"
    ],
    "durham/newton-aycliffe": [],
    "durham/seaham": [
        "Seaham Harbour",
        "Seaham, County Durham"
    ],
    "durham/spennymoor": [
        "Spennymoor Settlement"
    ],
    "northumberland/alnwick": [
        "Alnwick, England",
        "Alnwick Fayre",
        "Alnwick, Northumberland",
        "Alnwick Fair"
    ],
    "northumberland/hexham": [
        "Hexham, England",
        "Hexham, Northumberland",
        "Hexham riot",
        "Hexham, Great Britain"
    ],
    "northumberland/morpeth": [
        "Morpeth, Northumberland",
        "Morpeth, England",
        "Morpeth UK"
    ],
    "northumberland/berwick-upon-tweed": [
        "Berwick-on-Tweed",
        "Berwick",
        "Berwick-upon-Tweed, Northumberland"
    ],
    "northumberland/ashington": [
        "Ashington, Northumberland"
    ],
    "northumberland/blyth": [
        "Blyth, Northumberland",
        "Blyth Sands",
        "Blyth High Light",
        "Blyth Harbour",
        "Port of Blyth",
        "Blyth Harbour Commissioners",
        "Blyth Harbour Commission"
    ],
    "northumberland/cramlington": [
        "East Cramlington",
        "Cramlington, Northumberland",
        "East Cramlington, Northumberland"
    ],
    "northumberland/prudhoe": [
        "Prudhoe Mill",
        "Low Prudhoe"
    ],
    "northumberland/amble": [
        "Amble by the Sea",
        "Amble-by-the-sea",
        "Amble by the Sea, Northumberland",
        "Amble, Northumberland"
    ],
    "teesside/billingham": [
        "Billingham Forum",
        "Billingham, England",
        "Billingham Forum Ice Rink",
        "Billingham Urban District",
        "Billingham-on-Tees",
        "Billingham, County Durham"
    ],
    "teesside/guisborough": [
        "St. Nicholas's Church, Guisborough"
    ],
    "tyne-and-wear/houghton-le-spring": [
        "Houghton-le-Spring, Durham"
    ],
    "west-yorkshire/leeds": [
        "Leeds, England",
        "Leeds, Yorkshire",
        "Leeds, UK",
        "Leeds, West Yorkshire",
        "Higher Education in Leeds",
        "The weather in Leeds",
        "Leeds, United Kingdom",
        "Leeds - Bradford, UK"
    ],
    "west-yorkshire/bradford": [
        "Bradford, Yorkshire",
        "Bradford, West Yorkshire",
        "Bradford, England",
        "Central Bradford",
        "Bradford city centre",
        "Bradford Pals",
        "Bradford, West Yorkshire, England",
        "Bradford, UK"
    ],
    "west-yorkshire/wakefield": [
        "Wakefield, England",
        "Wakefield, Yorkshire",
        "Wakefield, West Yorkshire",
        "County Borough of Wakefield",
        "Wakefield Rural District",
        "Wakefield, UK",
        "East Moor, Wakefield",
        "Wakefield Harriers"
    ],
    "west-yorkshire/huddersfield": [
        "Huddersfield, England",
        "Huddersfield Grammar School",
        "County Borough of Huddersfield",
        "Huddersfield, West Yorkshire",
        "Huddersfield, Yorkshire",
        "Huddersfield Corporation"
    ],
    "west-yorkshire/halifax": [
        "Halifax, West Yorkshire",
        "Halifax, Yorkshire",
        "Halifax, England",
        "County Borough of Halifax",
        "Halifax Courier",
        "Halifax, West Yorkshire, England",
        "Halifax, UK",
        "Halifax, West Riding of Yorkshire"
    ],
    "west-yorkshire/keighley": [
        "Municipal Borough of Keighley",
        "Keighley, Yorkshire",
        "Keighley, England",
        "Keighley, West Yorkshire",
        "Keighley, West Riding of Yorkshire",
        "Keighley Corporation"
    ],
    "west-yorkshire/ilkley": [
        "Ilkley, West Yorkshire",
        "Ilkley Urban District",
        "Ilkley Ward",
        "Ilkley College of Education",
        "Ilkley College",
        "Ilkley Clean River Campaign"
    ],
    "west-yorkshire/dewsbury": [
        "County Borough of Dewsbury",
        "Dewsbury, West Yorkshire"
    ],
    "west-yorkshire/batley": [
        "Municipal Borough of Batley",
        "Mill Lane School, Batley",
        "Batley, Yorkshire",
        "Batley, West Yorkshire"
    ],
    "west-yorkshire/morley": [
        "Morley, West Yorkshire",
        "Morley Victoria Primary School",
        "Morley, West Yorkshire, England",
        "Morley, West Riding of Yorkshire"
    ],
    "west-yorkshire/pudsey": [
        "Pudsey, Leeds",
        "Fartown, Pudsey"
    ],
    "south-yorkshire/sheffield": [
        "Sheffield, England",
        "City of Sheffield Youth Orchestra",
        "City Sheffield Youth Orchestra",
        "Sheffield Symphony Orchestra",
        "Sheffield Philharmonic Orchestra",
        "Sheffield, Great Britain",
        "Sheffield, UK",
        "Sheffield england"
    ],
    "south-yorkshire/doncaster": [
        "Doncaster, England",
        "Doncaster, South Yorkshire",
        "The weather in Doncaster",
        "County Borough of Doncaster",
        "Doncaster urban area",
        "Doncaster, Yorkshire"
    ],
    "south-yorkshire/rotherham": [
        "Rotherham, England",
        "County Borough of Rotherham",
        "Rotherham Rural District",
        "Rotherham, UK",
        "Rotherham, South Yorkshire",
        "Rotherham, Yorkshire"
    ],
    "south-yorkshire/barnsley": [
        "Barnsley, England",
        "Barnsley, South Yorkshire",
        "Barnsley, Yorkshire",
        "The Civic, Barnsley"
    ],
    "north-yorkshire/york": [
        "York, Yorkshire",
        "York, England",
        "York UA",
        "York, North Yorkshire",
        "The weather in York",
        "Yorkish",
        "County Borough of York",
        "York, UK"
    ],
    "north-yorkshire/harrogate": [
        "Harrogate, England",
        "Harrogate, North Yorkshire",
        "South stanley harrogate",
        "Low Harrogate",
        "Harlow Hill, Harrogate",
        "Harrogate Built-up area",
        "Municipal Borough of Harrogate",
        "Harrogate Corporation"
    ],
    "north-yorkshire/scarborough": [
        "Scarborough, North Yorkshire",
        "Scarborough, Yorkshire",
        "Scarborough, England",
        "Scarborough, United Kingdom",
        "Scarborough Pier",
        "Municipal Borough of Scarborough"
    ],
    "north-yorkshire/skipton": [
        "Skipton-in-Craven",
        "Skipton, England",
        "Skipton, Yorkshire",
        "Skipton, North Yorkshire",
        "Skipton in Craven"
    ],
    "north-yorkshire/whitby": [
        "Whitby, North Yorkshire",
        "Whitby, Yorkshire",
        "Whitby, England"
    ],
    "north-yorkshire/malton": [
        "Malton, North Yorkshire",
        "Malton, Yorkshire",
        "Malton, North Riding of Yorkshire",
        "New Malton",
        "Malton, England"
    ],
    "north-yorkshire/northallerton": [
        "Northallerton, North Yorkshire",
        "Northallerton, Yorkshire"
    ],
    "north-yorkshire/thirsk": [
        "Old Thirsk",
        "Old Thirsk, North Yorkshire",
        "Thirsk, North Yorkshire"
    ],
    "north-yorkshire/knaresborough": [
        "Knaresborough town mayor",
        "Town Mayors of Knaresborough"
    ],
    "north-yorkshire/selby": [
        "Selby, Yorkshire",
        "Selby, North Yorkshire"
    ],
    "west-yorkshire/wetherby": [
        "Wetherby, West Yorkshire",
        "Wetherby, Leeds"
    ],
    "west-yorkshire/pontefract": [
        "Pontefract, England",
        "Pontefract, UK",
        "Municipal Borough of Pontefract",
        "Pontefract district",
        "Pontefract, West Yorkshire",
        "Pontefract, United Kingdom"
    ],
    "west-yorkshire/castleford": [
        "Castleford, West Yorkshire",
        "Castleford, England",
        "Castleford, Yorkshire"
    ],
    "north-yorkshire/ripon": [
        "Ripon, North Yorkshire",
        "Ripon, Yorkshire",
        "City of Ripon, Yorkshire",
        "City of Ripon, North Yorkshire",
        "Ripon, England",
        "Ripon hornblower",
        "Ripon, UK",
        "Ripon Abbey"
    ],
    "east-riding-of-yorkshire/hull": [
        "Hull",
        "City of Kingston upon Hull",
        "City of Kingston upon Hull, United Kingdom",
        "County Borough of Kingston upon Hull",
        "Kingston upon Hull, East Riding of Yorkshire"
    ],
    "east-riding-of-yorkshire/beverley": [
        "Beverley, East Riding of Yorkshire",
        "Beverley, England",
        "Beverley, Yorkshire",
        "Beverley town fair"
    ],
    "east-riding-of-yorkshire/bridlington": [
        "Marton, Bridlington",
        "Bridlington, East Riding of Yorkshire",
        "Bridlington, Yorkshire"
    ],
    "east-riding-of-yorkshire/goole": [
        "Goole, East Riding of Yorkshire",
        "Goole, Yorkshire",
        "Goole, East Yorkshire",
        "Goole, United Kingdom"
    ],
    "derbyshire/derby": [
        "Derby, Derbyshire, England",
        "Derby UA",
        "Derby, Derbyshire",
        "City of Derby",
        "Derby, England",
        "Derby City, England",
        "West End of Derby",
        "County Borough of Derby"
    ],
    "derbyshire/chesterfield": [
        "Chesterfield, Derbyshire",
        "Chesterfield, Derbyshire, England",
        "Chesterfield coach station",
        "Chesterfield Urban Area"
    ],
    "derbyshire/buxton": [
        "Buxton, Derbyshire, England",
        "Buxton, Derbyshire",
        "Buxton water"
    ],
    "derbyshire/matlock": [
        "Matlock, Derbyshire",
        "Matlock Town",
        "Matlock, England",
        "Matlock Bank",
        "Matlock Green"
    ],
    "nottinghamshire/nottingham": [
        "Nottingham, England",
        "Nottingham UA",
        "City of Nottingham",
        "Nottingham, Nottinghamshire",
        "Nottingham, UK",
        "Nottingham, United Kingdom",
        "Bracebridge, Nottinghamshire",
        "County Borough of Nottingham"
    ],
    "nottinghamshire/mansfield": [
        "Mansfield, Nottinghamshire",
        "Mansfield Nottinghamshire England",
        "Mansfield, England",
        "Mansfield, United Kingdom",
        "Mansfield, Notts."
    ],
    "nottinghamshire/newark-on-trent": [
        "Newark",
        "Newark-on-Trent, Nottinghamshire",
        "Beacon, Newark-on-Trent",
        "Bridge, Newark-on-Trent",
        "Castle, Newark-on-Trent",
        "Devon, Newark-on-Trent",
        "Sleaford, Newark-on-Trent",
        "Magnus, Newark-on-Trent"
    ],
    "nottinghamshire/worksop": [
        "Worksop, Bassetlaw",
        "Worksop, England",
        "Worksop, Nottinghamshire"
    ],
    "nottinghamshire/retford": [
        "East Retford",
        "West Retford",
        "Thrumpton, Retford"
    ],
    "nottinghamshire/beeston": [
        "Beeston, Nottinghamshire",
        "Victoria Hotel, Beeston",
        "Beeston canal",
        "Beeston, Nottingham",
        "Beeston Rylands",
        "Beeston Fields"
    ],
    "derbyshire/long-eaton": [
        "St lawrence school long eaton"
    ],
    "derbyshire/ilkeston": [
        "Ilkeston, Derbyshire"
    ],
    "leicestershire/leicester": [
        "Leicester UA",
        "Leicester, England",
        "City of Leicester",
        "Leicester, United Kingdom",
        "Leicesterians",
        "Leicester, Leicestershire",
        "Leicester, UK",
        "County Borough of Leicester"
    ],
    "leicestershire/loughborough": [
        "Loughborough, England",
        "Loughborough Library",
        "Town Hall, Loughborough",
        "Loughborough, Leicestershire",
        "Loughborough, United Kingdom",
        "Loughborough, Great Britain"
    ],
    "leicestershire/hinckley": [
        "Hinckley, Leicestershire"
    ],
    "leicestershire/melton-mowbray": [
        "Melton Mowbray Urban District",
        "Melton Mowbray, Leicestershire"
    ],
    "leicestershire/market-harborough": [
        "Old Grammar School, Market Harborough",
        "Market Harborough, England"
    ],
    "leicestershire/coalville": [
        "Coalville, Leicestershire",
        "Coalville, Leicester"
    ],
    "lincolnshire/lincoln": [
        "Lincoln, England",
        "Lincoln, United Kingdom",
        "England Lincoln",
        "St Giles Lincoln",
        "County Borough of Lincoln",
        "City of Lincoln",
        "Lincoln, Lincolnshire",
        "Lincoln Heath"
    ],
    "lincolnshire/grimsby": [
        "Great Grimsby",
        "Grimsby, England",
        "Grimsby, Lincolnshire",
        "County Borough of Grimsby",
        "Grimsby Town Council",
        "Grimsby Corporation",
        "Grimsby, North East Lincolnshire",
        "Grimsby built-up area"
    ],
    "lincolnshire/boston": [
        "Boston, Lincolnshire",
        "Boston, England",
        "Boston, uk",
        "Boston, Lincs"
    ],
    "lincolnshire/grantham": [
        "Grantham, England",
        "Grantham, Lincolnshire",
        "Mayor of Grantham",
        "The Grantham Journal",
        "Alderman of Grantham",
        "Grantham Journal",
        "Earlesfield, Grantham",
        "Harrowby, Grantham"
    ],
    "lincolnshire/scunthorpe": [
        "Scunthorpe, Lincolnshire",
        "Scunthorpe, North Lincolnshire"
    ],
    "lincolnshire/skegness": [
        "Skegness, England",
        "Skegness Airfield",
        "Skegness, Lincolnshire"
    ],
    "lincolnshire/spalding": [
        "Spalding, Lincolnshire",
        "Spalding, England",
        "Spalding, Lincs"
    ],
    "lincolnshire/sleaford": [
        "New Sleaford",
        "Sleaford, England",
        "Sleaford, Lincolnshire",
        "Sleaford Town Runners",
        "Sleaford Islamic Centre",
        "Sleaford Mosque"
    ],
    "lincolnshire/gainsborough": [
        "Gainsborough, Lincolnshire",
        "Gainsborough-on-Trent",
        "Gainsborough North West",
        "Gainsborough North East",
        "Gainsborough Hill"
    ],
    "lincolnshire/cleethorpes": [
        "Cleethorpes, Lincolnshire",
        "Cleethorpes UFO sighting",
        "Cleethorpes, North East Lincolnshire"
    ],
    "lincolnshire/stamford": [
        "Stamford, Lincolnshire",
        "Stamford, England",
        "Education in Stamford, Lincolnshire",
        "Bibliography of Stamford"
    ],
    "lincolnshire/louth": [
        "Louth, Lincolnshire",
        "Louth, England",
        "St James', Louth",
        "St Margaret's, Louth",
        "St Mary's, Louth",
        "St Michael's, Louth",
        "Trinity, Louth"
    ],
    "lincolnshire/bourne": [
        "Bourne, Lincolnshire",
        "Bourne Civic Society",
        "Bourne Abbey Church of England Academy",
        "Bourne Westfield Primary School",
        "Westfield School, Bourne",
        "Bourne Abbey Church of England School"
    ],
    "northamptonshire/northampton": [
        "Northampton, England",
        "Northampton, Northamptonshire",
        "Northampton, United Kingdom",
        "County Borough of Northampton",
        "Northampton Clown",
        "Northampton, England, UK",
        "Borough of Northampton"
    ],
    "northamptonshire/kettering": [
        "Kettering, Northamptonshire",
        "Kettering, Northhamptonshire",
        "Kettering, England",
        "St Peter's School, Kettering"
    ],
    "northamptonshire/corby": [
        "Corby, England",
        "Corby, Northamptonshire",
        "Corby Technical School",
        "Corby, United Kingdom"
    ],
    "northamptonshire/wellingborough": [
        "Wellingborough, Northamptonshire",
        "Wellingborough, England"
    ],
    "northamptonshire/rushden": [
        "Rushden, England",
        "Rushden, Northamptonshire",
        "Rushden, United Kingdom"
    ],
    "northamptonshire/daventry": [
        "Daventry, Northamptonshire"
    ],
    "northamptonshire/towcester": [
        "Towcester, Northamptonshire",
        "Towcester C of E Primary School"
    ],
    "northamptonshire/brackley": [
        "Brackley, Northamptonshire",
        "Brackley Castle"
    ],
    "rutland/oakham": [
        "Oakham, England",
        "Oakham Rugby Club",
        "Oakham's horseshoes",
        "Oakham's horseshoe"
    ],
    "west-midlands/birmingham": [
        "Birmingham, UK",
        "England Birmingham",
        "Birmingham artistic figures",
        "Birmingham Heritage Festival",
        "City of Birmingham",
        "Metropolitan Borough of Birmingham",
        "Birmingham, West Midlands",
        "Birmingham, United Kingdom"
    ],
    "west-midlands/coventry": [
        "London",
        "Birmingham",
        "Leeds",
        "Glasgow",
        "Sheffield",
        "Manchester",
        "Bradford",
        "Edinburgh"
    ],
    "west-midlands/wolverhampton": [
        "Wolverhampton, England",
        "City of Wolverhampton",
        "Metropolitan Borough of Wolverhampton",
        "Wolverhamptonshire",
        "County Borough of Wolverhampton",
        "Wolverhampton, West Midlands",
        "The City of Wolverhampton",
        "Wolverhampton, West Midlands, England, UK"
    ],
    "west-midlands/solihull": [
        "Solihull, West Midlands",
        "County Borough of Solihull",
        "Solihull, Warwickshire",
        "Solihull, Birmingham"
    ],
    "west-midlands/walsall": [
        "Walsall, England",
        "County Borough of Walsall",
        "Walsall, UK",
        "Walsall, United Kingdom",
        "Walsall, Staffordshire",
        "Walsall, West Midlands"
    ],
    "west-midlands/dudley": [
        "Dudley, England",
        "Dudley, UK",
        "Dudley, Worcestershire",
        "Dudley, West Midlands",
        "Dudley town centre"
    ],
    "west-midlands/sutton-coldfield": [
        "Royal Sutton Coldfield",
        "The Royal Town of Sutton Coldfield",
        "Royal Town of Sutton Coldfield",
        "Sutton Coldfield Parish Council",
        "Sutton Coldfield, Birmingham",
        "Sutton Coldfield, Birmingham, West Midlands"
    ],
    "west-midlands/west-bromwich": [
        "West Brom",
        "West Bromwich, England",
        "West Bromwich County Borough",
        "County Borough of West Bromwich",
        "West Bromwich, Sandwell",
        "West Bromwich Borough Council",
        "West Bromwich, Staffordshire"
    ],
    "west-midlands/halesowen": [
        "Halesowen, Shropshire"
    ],
    "west-midlands/stourbridge": [],
    "staffordshire/stoke-on-trent": [
        "Stoke",
        "Stoke-on-Trent UA",
        "City of Stoke-on-Trent",
        "Stoke-on-Trent, Staffordshire",
        "Stoke-on-Trent, North Staffordshire",
        "County Borough of Stoke-on-Trent"
    ],
    "staffordshire/stafford": [
        "Stafford, England",
        "Stafford, Staffordshire",
        "Wildwood, Stafford",
        "St. Bede's Preparatory School, Stafford",
        "Parkside, Stafford",
        "Stafford Corporation"
    ],
    "staffordshire/burton-upon-trent": [
        "Burton-on-Trent",
        "Burton",
        "County Borough of Burton upon Trent",
        "Burton upon Trent Borough Council"
    ],
    "staffordshire/tamworth": [
        "Tamworth, Staffordshire",
        "Tamworth, England",
        "Borough of Tamworth",
        "Tamworth Built-up area",
        "Tamworth Hoard"
    ],
    "staffordshire/lichfield": [
        "City of Lichfield",
        "Municipal Borough of Lichfield",
        "Lichfield City",
        "Lichfield School",
        "Lichfield, Staffordshire",
        "St John's, Lichfield",
        "Stowe, Lichfield",
        "St Johns, Lichfield"
    ],
    "warwickshire/warwick": [
        "Warwick, England",
        "Warwick Gates",
        "Warwick, Warwickshire",
        "Warwick, United Kingdom",
        "Warwick, UK"
    ],
    "warwickshire/nuneaton": [
        "Nuneaton, England",
        "Nuneaton, Warwickshire",
        "Nuneaton Urban Area",
        "Municipal Borough of Nuneaton"
    ],
    "warwickshire/rugby": [
        "Rugby, Warwickshire",
        "Rugby, England",
        "Rugby Golf Club",
        "Rugby, UK",
        "Rugby Advertiser"
    ],
    "warwickshire/stratford-upon-avon": [
        "Stratford",
        "Stratford-upon-Avon, Warwickshire",
        "Stratford-upon-Avon, United Kingdom",
        "Stratford-upon-Avon Herald",
        "The Stratford-upon-Avon Herald"
    ],
    "warwickshire/leamington-spa": [
        "Leamington Spa",
        "Leamington",
        "Lem",
        "Leam",
        "Leamington Priors"
    ],
    "warwickshire/kenilworth": [
        "Kenilworth, Warwickshire",
        "Kenilworth, England",
        "Kenilworth festival"
    ],
    "warwickshire/bedworth": [
        "Bedworth Heath",
        "Bedworth Heath, Warwickshire",
        "Bedworth Urban District",
        "Bedworth, Warwickshire"
    ],
    "worcestershire/worcester": [
        "Worcester, England",
        "Worcester, United Kingdom",
        "Worcester, Great Britain",
        "Worcester, Worcestershire",
        "Worcester, UK",
        "The weather in Worcester",
        "Manufacturing in Worcester",
        "City of Worcester"
    ],
    "worcestershire/malvern": [],
    "worcestershire/redditch": [
        "Redditch, England",
        "Redditch, Worcestershire",
        "Borough of Redditch"
    ],
    "worcestershire/kidderminster": [
        "Kidderminster, England",
        "Kidderminster carpet industry",
        "Kidderminster Urban Area",
        "Kidderminster, Worcestershire"
    ],
    "worcestershire/bromsgrove": [
        "Bromsgrove, England",
        "Bromsgrove Society",
        "Bromsgrove, Worcestershire"
    ],
    "worcestershire/droitwich": [
        "Droitwich",
        "Droitwich Spa, Worcestershire"
    ],
    "shropshire/shrewsbury": [
        "Shrewsbury, England",
        "Shrewsbury, Shropshire, England",
        "Shrewsbury, United Kingdom",
        "Shrewsbury, Shropshire",
        "Shrewsbury in the arts",
        "Shrewsbury, UK"
    ],
    "shropshire/telford": [
        "Telford, Shropshire",
        "Telford, England",
        "Telford urban area",
        "Telford New Town"
    ],
    "herefordshire/hereford": [
        "Hereford, England",
        "Hereford, Herefordshire",
        "Radio stations in Hereford",
        "Hereford City Council",
        "City of Hereford",
        "Victoria Park, Hereford"
    ],
    "herefordshire/leominster": [
        "Leominster, England",
        "Leominster, Herefordshire"
    ],
    "essex/chelmsford": [
        "Clockwise from top, left to right",
        "Chelmsford, Essex",
        "Chelmsford,Essex",
        "Chelmsford, England",
        "Municipal Borough of Chelmsford",
        "The weather in Chelmsford",
        "Chelmsford, United Kingdom",
        "Chelmsford, Essex, UK"
    ],
    "essex/colchester": [
        "Colchester, Essex",
        "Colchester, England",
        "The weather in Colchester",
        "Colchester Film Festival",
        "Parish council elections in Colchester",
        "Colchester Borough Parish Council elections",
        "Municipal Borough of Colchester",
        "Colchester Municipal Borough"
    ],
    "essex/southend-on-sea": [
        "Southend",
        "Southend-On-Sea, Essex",
        "Southend-on-Sea District",
        "Borough of Southend-on-Sea",
        "Southend-on-Sea, England",
        "City of Southend-on-Sea"
    ],
    "essex/basildon": [
        "Basildon, England",
        "Basildon, Essex",
        "Basildon New Town"
    ],
    "essex/brentwood": [
        "Brentwood, Essex",
        "Brentwood, England",
        "Brentwood Essex",
        "Brentwood Urban District",
        "Brentwood, UK",
        "Brentwood Preparatory School",
        "Brentwood Centre Arena",
        "Brentwood Centre"
    ],
    "essex/harlow": [
        "Harlow, England",
        "Harlow Urban District",
        "Harlow, Essex",
        "Harlow New Town",
        "Latton, Harlow"
    ],
    "essex/braintree": [
        "Braintree, Essex",
        "Braintree, England",
        "Braintree United"
    ],
    "essex/clacton-on-sea": [
        "Clacton",
        "Clacton-on-Sea, England",
        "Clacton-on-Sea, Essex"
    ],
    "essex/grays": [
        "Grays, Essex",
        "Grays Thurrock",
        "Grays Thurrock Urban District",
        "Grays Urban District"
    ],
    "essex/harwich": [
        "Harwich, England",
        "Harwich, Essex",
        "Harwich Harbour"
    ],
    "essex/rayleigh": [
        "Rayleigh, Essex",
        "Rayleigh Urban District"
    ],
    "hertfordshire/st-albans": [
        "St Albans, England",
        "St Albans, Herts",
        "The weather in St Albans",
        "St Albans, Hertfordshire",
        "Municipal Borough of St Albans",
        "St Albans, United Kingdom"
    ],
    "hertfordshire/watford": [
        "Municipal Borough of Watford",
        "Watford, England",
        "Borough of Watford",
        "Watford, United Kingdom",
        "Watford Official Website",
        "Watford, Hertfordshire",
        "Watford, Great Britain"
    ],
    "hertfordshire/stevenage": [
        "Stevenage, England",
        "Queensway Stevenage",
        "Borough of Stevenage",
        "Stevenage Outer Orbital Path",
        "Stevenage Urban District",
        "The weather in Stevenage",
        "Stevenage, Hertfordshire",
        "Great Fire of Stevenage"
    ],
    "hertfordshire/hemel-hempstead": [
        "Hemel Hempstead, England",
        "Hemel Hempstead, Hertfordshire",
        "Municipal Borough of Hemel Hempstead"
    ],
    "hertfordshire/hertford": [
        "Hertford, England",
        "Hertford, Hertfordshire",
        "Hertford Kingsmead",
        "Hertford Sele",
        "Hertford Rural North",
        "Hertford Rural South",
        "Hertford Bengeo",
        "Hertford, United Kingdom"
    ],
    "hertfordshire/welwyn-garden-city": [
        "Welwyn Garden City, England",
        "Welwyn Garden City, Hertfordshire",
        "Welwyn Garden City Urban District"
    ],
    "hertfordshire/hatfield": [
        "Hatfield, Hertfordshire",
        "Hatfield Central",
        "Hatfield South",
        "Hatfield East",
        "Hatfield Villages",
        "Hatfield West",
        "Bishops Hatfield,"
    ],
    "hertfordshire/hitchin": [
        "Hitchin, England",
        "Hitchin Urban District",
        "Hitchin, Hertfordshire",
        "Hitchin, Herfordshire"
    ],
    "hertfordshire/bishops-stortford": [
        "Bishop's Stortford, Essex",
        "Bishop's Stortford All Saints",
        "Bishop's Stortford Central",
        "Bishop's Stortford Meads",
        "Bishop's Stortford Silverleys",
        "Bishop's Stortford South",
        "Bishop's Stortford, Hertfordshire",
        "Bishop's Stortford Urban District"
    ],
    "cambridgeshire/cambridge": [
        "Cambridge, England",
        "England Cambridge",
        "Cambridge, UK",
        "Cambridge, United Kingdom",
        "Honey Hill, Cambridge",
        "The weather in Cambridge",
        "Cambridge, Cambridgeshire",
        "Cambridge, East Anglia"
    ],
    "cambridgeshire/peterborough": [
        "Peterborough, England",
        "Municipal Borough of Peterborough",
        "Peterborough, Cambridgeshire",
        "The weather in Peterborough",
        "Magna Park, Peterborough",
        "Peterborough, United Kingdom",
        "Peterborough, Cambs",
        "Great Fire of Peterborough"
    ],
    "cambridgeshire/huntingdon": [
        "St. Peter's Secondary School, Huntingdon"
    ],
    "cambridgeshire/ely": [
        "Ely, Cambridgeshire",
        "City of Ely",
        "Ely, England",
        "Ely Martyrs",
        "Liberty of Ely"
    ],
    "norfolk/norwich": [
        "Norwich, England",
        "Norwich, Norfolk",
        "Norwich, UK",
        "Norwich uk",
        "Norwich, East Anglia",
        "Norwich, United Kingdom",
        "County Borough of Norwich",
        "Education in Norwich"
    ],
    "norfolk/great-yarmouth": [
        "Yarmouth",
        "Great Yarmouth First Responders",
        "County Borough of Great Yarmouth",
        "Great Yarmouth Dockyard",
        "Great Yarmouth, Norfolk"
    ],
    "norfolk/kings-lynn": [
        "and colloquially as",
        "King's Lynn, Norfolk",
        "Borough of King's Lynn",
        "King's Lynne",
        "Siege of King's Lynn"
    ],
    "norfolk/thetford": [
        "Thetford, England",
        "Thetford, Norfolk"
    ],
    "norfolk/cromer": [
        "Cromer, England",
        "Cromer, Norfolk",
        "Cromer Parish Church",
        "Cromer, Norfolk, England"
    ],
    "norfolk/dereham": [
        "East Dereham",
        "East Dereham, Norfolk",
        "Dereham, Norfolk",
        "East Dereham Urban District Council"
    ],
    "norfolk/wymondham": [
        "Wymondham, Norfolk",
        "Wymondham Manor"
    ],
    "suffolk/ipswich": [
        "Ipswich, Suffolk, England",
        "Ipswich, England",
        "Ipswich, UK",
        "County Borough of Ipswich",
        "Borough of Ipswich",
        "Ipswich county borough",
        "Municipal Borough of Ipswich",
        "Ipswich Garden Suburb"
    ],
    "suffolk/bury-st-edmunds": [
        "Bury St Edmunds, England",
        "Bury St Edmunds, Suffolk"
    ],
    "suffolk/lowestoft": [
        "Lowestoft Mayor",
        "Lowestoft, Suffolk"
    ],
    "suffolk/felixstowe": [
        "Old Felixstowe",
        "Felixstowe, Suffolk"
    ],
    "suffolk/sudbury": [
        "Sudbury, Suffolk",
        "Catholic Church in Sudbury, Suffolk"
    ],
    "suffolk/newmarket": [
        "Newmarket, Suffolk",
        "Newmarket, England",
        "Newmarket's",
        "Newmarket Urban District",
        "Newmarket, Suffolk, UK",
        "Newmarket, Suffolk, United Kingdom",
        "Newmarket Town Council"
    ],
    "suffolk/stowmarket": [
        "Stowmarket Town Council"
    ],
    "suffolk/woodbridge": [
        "Woodbridge, Suffolk",
        "Woodbridge Division, Suffolk"
    ],
    "suffolk/haverhill": [
        "Haverhill, Suffolk",
        "Haverhill, England",
        "Great Fire of Haverhill",
        "Haverhill Urban District Council"
    ],
    "bedfordshire/bedford": [
        "Bedford, England",
        "Bedford, Bedfordshire",
        "The weather in Bedford",
        "Bedford Urban Area",
        "Great Fire of Bedford",
        "Great Flood of Bedford",
        "Municipal Borough of Bedford",
        "Education in Bedford"
    ],
    "bedfordshire/luton": [
        "Luton, UK",
        "Luton, England",
        "County of Luton",
        "Culture in Luton",
        "Lutonian",
        "The weather in Luton",
        "Borough of Luton",
        "County Borough of Luton"
    ],
    "bedfordshire/dunstable": [
        "Dunstable, England",
        "Dunstable, Bedfordshire",
        "Capture of Dunstable"
    ],
    "greater-london/tower-hamlets": [
        "London Borough of Tower Hamlets",
        "Tower Hamlets, London",
        "The London Borough of Tower Hamlets"
    ],
    "greater-london/city-of-london": [
        "the City",
        "the Square Mile",
        "The City of London",
        "City of London and its liberties",
        "County of the City of London",
        "City and County of the City of London"
    ],
    "greater-london/westminster": [
        "Westminster, London, England",
        "Westminster, England",
        "Westminster, London"
    ],
    "greater-london/camden": [],
    "greater-london/hackney": [],
    "greater-london/islington": [
        "Islington, London, England",
        "Islington, London",
        "Islington High Street",
        "Islington, Middlesex"
    ],
    "greater-london/southwark": [
        "Borough",
        "Liberty of Southwark",
        "Southwark, London"
    ],
    "greater-london/lambeth": [
        "Lambeth, London, England",
        "South Lambeth",
        "North Lambeth",
        "Lambeth, London",
        "Lambeth, England",
        "Lambeth, UK"
    ],
    "greater-london/kensington-and-chelsea": [],
    "greater-london/greenwich": [
        "Greenwich, England",
        "Greenwich, London, England",
        "Greenwich, London",
        "Greenwich Market",
        "Greenwich Visitor Centre",
        "Maritime Greenwich",
        "Greenwich, UK",
        "Greenwich District"
    ],
    "greater-london/newham": [
        "London Borough of Newham",
        "Borough of Newham",
        "Newham, East London"
    ],
    "greater-london/ealing": [
        "Ealing Broadway",
        "Little Ealing",
        "Ealing, London",
        "Ealing Liberal Synagogue",
        "Ealing, Middlesex",
        "Ealing, United Kingdom",
        "Ealing Broadway BID",
        "Great Ealing"
    ],
    "greater-london/hillingdon": [
        "Hillingdon Heath",
        "Hillingdon East Parish Council",
        "Hillingdon East",
        "Hillingdon, Middlesex",
        "North Hillingdon",
        "Hillingdon, Greater London",
        "Hillingdon, London",
        "Hillingdon, Great Britain"
    ],
    "greater-london/richmond-upon-thames": [
        "London Borough of Richmond upon Thames",
        "The London Borough of Richmond Upon Thames"
    ],
    "greater-london/croydon": [
        "Croydon, London, England",
        "Croydon, Surrey",
        "Croydon, London",
        "Croydon, United Kingdom",
        "Croydon, England",
        "Croydon town centre",
        "Croydon BID"
    ],
    "kent/maidstone": [
        "Maidstone, England",
        "Maidstone, Kent",
        "Maidstone,Kent"
    ],
    "kent/canterbury": [
        "Canterbury, England",
        "Canterbury, Kent",
        "Canterbury City Center",
        "Canterbury, United Kingdom",
        "Universities in Canterbury",
        "St. Alphege, Canterbury"
    ],
    "kent/dover": [
        "Dover, England",
        "Dover, Kent",
        "Docks Of Dover",
        "Dover RFC",
        "The weather in Dover",
        "Charlton by Dover"
    ],
    "kent/tunbridge-wells": [
        "Tunbridge Wells",
        "Royal Tunbridge Wells, Kent"
    ],
    "kent/ashford": [
        "Ashford, Kent",
        "Ashford, England"
    ],
    "kent/chatham": [
        "Chatham, Kent",
        "Chatham, England",
        "Chatham Maritime",
        "Chatham, Kent, England",
        "Chatham, Medway",
        "Trafalgar Centre, Chatham"
    ],
    "kent/gillingham": [
        "Gillingham, Kent",
        "Gillingham kent",
        "Gillingham, Medway"
    ],
    "kent/dartford": [
        "Municipal Borough of Dartford",
        "Dartford, England",
        "Dartford, Kent"
    ],
    "kent/gravesend": [
        "Gravesend, England",
        "Gravesend RFC",
        "Municipal Borough of Gravesend",
        "Gravesend, Kent",
        "Gravesend Hospital"
    ],
    "kent/folkestone": [
        "Folkestone, Kent",
        "Folkestone, England",
        "St Martins C.E.P. School Folkestone",
        "Radio Folkestone",
        "Academy FM Folkestone"
    ],
    "kent/margate": [
        "Margate, England",
        "Margate, Kent",
        "Municipal Borough of Margate",
        "Margate Beach"
    ],
    "kent/sevenoaks": [
        "Sevenoaks, England",
        "Sevenoaks Urban District",
        "Sevenoaks, Kent"
    ],
    "surrey/guildford": [
        "Clockwise from top left",
        "Guildford, Surrey",
        "Guildford, England",
        "Holy Trinity School, Guildford",
        "Guildford Grove School",
        "Holy Trinity Junior School, Guildford",
        "Westborough Guildford",
        "Guildford Park"
    ],
    "surrey/woking": [
        "Borough of Woking",
        "Woking, Surrey",
        "Woking Community Hospital",
        "Woking Hospital",
        "Hook Heath, Woking",
        "Woking, England"
    ],
    "surrey/epsom": [
        "Epsom, Surrey",
        "Epsom, England"
    ],
    "surrey/reigate": [
        "Reigate, Surrey"
    ],
    "surrey/camberley": [
        "Yorktown",
        "Camberley Theatre",
        "Camberley, Surrey",
        "Camberley, England"
    ],
    "surrey/farnham": [
        "Farnham, Surrey",
        "Farnham Hundred",
        "Farnham, Hampshire",
        "Farnham, UK",
        "Farnham, England",
        "Farnham Residents"
    ],
    "surrey/staines": [
        "Staines",
        "Staines-upon-Thames, England"
    ],
    "surrey/redhill": [
        "Redhill, Surrey"
    ],
    "east-sussex/brighton": [
        "Brighton, England",
        "Brighton, UK",
        "Brighton, East Sussex",
        "Brighton, Sussex",
        "Mayor of Brighton",
        "Brighton music",
        "Homelessness in Brighton",
        "Brighton, United Kingdom"
    ],
    "east-sussex/eastbourne": [
        "Eastbourne, England",
        "Eastbourne, East Sussex",
        "Eastbourne Local History Society",
        "County Borough of Eastbourne",
        "The Eastbourne Local Historian",
        "Eastbourne Local Historian",
        "Eastbourne, Sussex"
    ],
    "west-sussex/crawley": [
        "Crawley, England",
        "The weather in Crawley",
        "Crawley, Sussex",
        "Crawley, West Sussex",
        "Borough of Crawley",
        "Crawley Leisure Park"
    ],
    "west-sussex/worthing": [
        "Worthing, West Sussex",
        "Worthing, England",
        "Worthing, Sussex",
        "Worthing District"
    ],
    "west-sussex/chichester": [
        "Chichester, England",
        "Chichester, West Sussex",
        "Chichester Conservation Area",
        "Chichester, Sussex",
        "Chichester Festivities",
        "Chichester City Council",
        "City of Chichester"
    ],
    "east-sussex/hastings": [
        "Hastings, East Sussex",
        "Hastings, England",
        "Hastings and St leonards",
        "Wishing Tree, Hastings",
        "Hastings town centre",
        "Baird, Hastings",
        "Hastings Town Center",
        "North Hastings"
    ],
    "west-sussex/horsham": [
        "Horsham in Sussex County, England",
        "Horsham, England",
        "Horsham, Sussex",
        "Horsham, West Sussex"
    ],
    "west-sussex/bognor-regis": [
        "Bognor",
        "Bognor Regis, Sussex"
    ],
    "east-sussex/lewes": [
        "Lewes, England",
        "Lewes, East Sussex"
    ],
    "hampshire/southampton": [
        "Southampton, England",
        "Southampton UA",
        "Southampton Council",
        "Southampton, Hampshire",
        "The weather in Southampton",
        "County Borough of Southampton",
        "City of Southampton",
        "Southampton, U.K."
    ],
    "hampshire/portsmouth": [
        "Portsmouth, England",
        "Portsmouth UA",
        "Portsmouth, Britain",
        "City of Portsmouth",
        "County Borough of Portsmouth",
        "Portsmouth, United Kingdom",
        "Portsmouth, Hampshire",
        "Portsmouth city centre"
    ],
    "hampshire/winchester": [
        "Winchester, England",
        "Winchester, Hampshire",
        "Winchester, UK"
    ],
    "hampshire/basingstoke": [
        "Basingstoke, England",
        "Basingstoke, UK",
        "Basingstoke, Hampshire",
        "Basingstoke, United Kingdom"
    ],
    "hampshire/fareham": [
        "Fareham, Hampshire"
    ],
    "hampshire/gosport": [
        "Gosport, England",
        "Gosport Council",
        "Borough of Gosport",
        "Gosport Lines",
        "Gosport peninsula",
        "Gosport, Hampshire",
        "Municipal Borough of Gosport"
    ],
    "hampshire/andover": [
        "Andover, Hampshire",
        "Andover, England",
        "Andover, Hants"
    ],
    "hampshire/farnborough": [
        "Farnborough, Hampshire",
        "Farnborough, Hants",
        "IQ Farnborough"
    ],
    "hampshire/aldershot": [
        "Aldershot, England",
        "Aldershot, Hampshire",
        "The Beatles in Aldershot",
        "Aldershot, Hants.",
        "Aldershot, United Kingdom",
        "Aldershot Lido"
    ],
    "berkshire/reading": [
        "Reading, Berkshire",
        "Reading England",
        "Reading UA",
        "Reading, England",
        "Borough of Reading",
        "Reading, berks",
        "Reading Explorer",
        "Reading Market"
    ],
    "berkshire/slough": [
        "Slough, England",
        "Slough, Berkshire",
        "Slough College",
        "Slough, Buckinghamshire"
    ],
    "berkshire/bracknell": [
        "Bracknell, England",
        "Bracknell, Berkshire",
        "St Joseph's Catholic Primary School, Bracknell",
        "St Joesphs primary school bracknell",
        "Bracknell, UK"
    ],
    "berkshire/windsor": [
        "Windsor, Berkshire",
        "New Windsor",
        "England Windsor",
        "Windsor, England",
        "Windsor, UK",
        "Municipal Borough of Windsor",
        "Municipal Borough of New Windsor",
        "New Windsor, Berkshire"
    ],
    "oxfordshire/oxford": [
        "Oxford, england",
        "Oxford, Oxfordshire",
        "City of Oxford",
        "Oxford, UK",
        "County Borough of Oxford",
        "The weather in Oxford",
        "Oxford, United Kingdom",
        "Cycling in Oxford"
    ],
    "oxfordshire/banbury": [
        "Banbury, England",
        "Banburyshire",
        "Banbury, Oxfordshire",
        "Banbury Cross",
        "Spiceball Park, Banbury",
        "People's Park, Banbury",
        "Bankside Park, Banbury",
        "St Louis Meadow Park, Banbury"
    ],
    "buckinghamshire/aylesbury": [
        "Aylesbury, Buckinghamshire",
        "Aylesbury Town Council",
        "Aylesbury, England",
        "Aylesbury Urban Area",
        "Aylesbury, United Kingdom"
    ],
    "buckinghamshire/high-wycombe": [
        "Wycombe",
        "High Wycombe Urban Area",
        "High Wycombe, Buckinghamshire",
        "High Wycombe Buckinghamshire",
        "High Wycombe, England",
        "High Wycombe Chair Making Museum",
        "High Wycombe, Bucks",
        "Municipal Borough of High Wycombe"
    ],
    "buckinghamshire/milton-keynes": [
        "Milton Keynes, England",
        "Milton Keynes Masterplan",
        "Milton Keynes master plan",
        "Milton Keynes Airport",
        "Milton Keynes University",
        "Milton Keynes, Buckinghamshire",
        "Milton Keynes, Great Britain"
    ],
    "isle-of-wight/newport-iow": [
        "Newport, Isle of Wight",
        "Newport, Hampshire",
        "Newport, IOW",
        "Newport, Isle of White"
    ],
    "isle-of-wight/ryde": [
        "Ryde, Isle of Wight"
    ],
    "devon/exeter": [
        "Exeter, England",
        "England Exeter",
        "Exeter, Devon",
        "The weather in Exeter",
        "County Borough of Exeter",
        "City of Exeter",
        "Underground passages, Exeter",
        "Mount Pleasant Park, Exeter"
    ],
    "devon/plymouth": [
        "Plymouth England",
        "Plymouth UA",
        "Plymouth, England",
        "England Plymouth",
        "Plymouth Devon",
        "City of Plymouth",
        "Plymouth, Devon",
        "Plymouth, Devonshire"
    ],
    "devon/torbay": [
        "Torbay UA",
        "Highway torbay",
        "Torbay, England",
        "County Borough of Torbay"
    ],
    "devon/barnstaple": [
        "Barnstaple, Devon"
    ],
    "cornwall/truro": [
        "Truro, Cornwall",
        "Truro, England",
        "The weather in Truro",
        "Truro City Council"
    ],
    "cornwall/newquay": [
        "Newquay, United Kingdom",
        "Newquay, England",
        "Newquay, Cornwall",
        "Newquay Surfing Reef",
        "Newquay Town Council"
    ],
    "cornwall/st-austell": [
        "St Austell parishes",
        "St Austell, Cornwall, UK"
    ],
    "cornwall/penzance": [
        "Penzance, Cornwall",
        "Penzance, United Kingdom",
        "Penzance, England",
        "Penzance Cricket Club",
        "Municipal Borough of Penzance"
    ],
    "somerset/taunton": [
        "Taunton, England",
        "Taunton, Somerset",
        "The weather in Taunton"
    ],
    "somerset/bath": [
        "Bath, Somerset",
        "Bath, England",
        "Bath, Avon",
        "City of Bath",
        "Bath england",
        "Georgian Bath",
        "Moorlands Junior School, Bath",
        "Bath Somerset"
    ],
    "somerset/yeovil": [
        "Yeovil, Somerset",
        "Yeovil Marsh, Somerset"
    ],
    "somerset/bridgwater": [
        "Bridgwater, England",
        "Bridgwater Arts Centre",
        "The weather in Bridgwater",
        "Bridgwater, Somerset"
    ],
    "somerset/wells": [
        "Wells, Somerset",
        "Wells, England",
        "City of Wells",
        "Wells, Somersetshire"
    ],
    "dorset/bournemouth": [
        "Bournemouth, England",
        "Bournemouth UA",
        "Bournemouth Eye",
        "Businesses in the Bournemouth area",
        "Businesses in Bournemouth",
        "Bournemouth, Dorset",
        "The weather in Bournemouth",
        "County Borough of Bournemouth"
    ],
    "dorset/poole": [
        "Poole UA",
        "Poole, Dorset",
        "Poole, England",
        "Poole, Dorsetshire",
        "The weather in Poole",
        "Poole Quay"
    ],
    "dorset/dorchester": [
        "Dorchester, Dorset",
        "Dorchester, Dorsetshire",
        "Dorchester Middle School"
    ],
    "dorset/weymouth": [
        "Weymouth, Dorset",
        "Weymouth, England",
        "Weymouth, Dorset weather",
        "The weather in Weymouth"
    ],
    "wiltshire/salisbury": [
        "England Salisbury",
        "Salisbury, England",
        "Salisbury, United Kingdom",
        "Salisbury, Wiltshire",
        "Salisbury Gas Light and Coke Company",
        "Salisbury Gas Company"
    ],
    "wiltshire/swindon": [
        "Swindon, England",
        "The weather in Swindon",
        "Swindon, Wiltshire"
    ],
    "wiltshire/trowbridge": [
        "Trowbridge, Wiltshire"
    ],
    "gloucestershire/gloucester": [
        "Gloucester, England",
        "Gloucester, Gloucestershire",
        "City of Gloucester",
        "Gloucester, United Kingdom",
        "County Borough of Gloucester",
        "Gloucester in the middle ages"
    ],
    "gloucestershire/cheltenham": [
        "Cheltenham Spa",
        "Cheltenham Gloucestershire",
        "Cheltenham, England",
        "Cheltenham, Gloucestershire",
        "Christ Church Cheltenham",
        "Lansdown Crescent, Cheltenham",
        "Cheltenham, UK",
        "Cheltenham, Clooucestershire"
    ],
    "gloucestershire/stroud": [
        "Stroud, England",
        "Stroudie",
        "Stroudy",
        "Stroud,Gloucestershire",
        "Stroud, Gloucestershire",
        "Stroud, Gloucestershire, United Kingdom"
    ],
    "bristol/bristol-city": [
        "Bristol, England",
        "City of Bristol",
        "City of Bristol, United Kingdom",
        "Bristolshire",
        "Bristol, UK",
        "Bristol, United Kingdom",
        "The weather in Bristol",
        "County Borough of Bristol"
    ],
    "south-glamorgan/cardiff": [
        "City and County of Cardiff",
        "Cardiff, Wales",
        "City of Cardiff",
        "Cardiffians",
        "East Cardiff",
        "The weather in Cardiff",
        "County Borough of Cardiff",
        "Cardiff, UK"
    ],
    "south-glamorgan/barry": [
        "Barry, Vale of Glamorgan",
        "Barry, Glamorgan",
        "Barry, South Glamorgan",
        "Gladstone,Barry",
        "Barry, Wales",
        "Gladstone, Barry",
        "Barry, Glamorganshire",
        "Barry, South Wales"
    ],
    "west-glamorgan/swansea": [
        "City and County of Swansea",
        "City of Swansea",
        "Swansea, United Kingdom",
        "Swansea, Wales",
        "The weather in Swansea",
        "County Borough of Swansea",
        "Swansea, Glamorganshire",
        "Swansea, South Wales"
    ],
    "west-glamorgan/neath": [
        "Neath, Neath Port Talbot",
        "Neath, Wales",
        "Neath, Glamorgan"
    ],
    "west-glamorgan/port-talbot": [
        "Port Talbot, Neath Port Talbot",
        "Port Talbot, Wales",
        "Port Talbot, Glamorgan",
        "Port Talbot, Glamorgan, Wales"
    ],
    "mid-glamorgan/bridgend": [
        "Bridgend, Wales",
        "Bridgend, Glamorgan"
    ],
    "mid-glamorgan/pontypridd": [
        "Pontypridd and Llantrisant Observer"
    ],
    "mid-glamorgan/merthyr-tydfil": [
        "Merthyr",
        "Merthyr Tydfill",
        "The Brunswick, Merthyr Tydfil",
        "Merthyr Tydfil, Wales",
        "Merthyr Tydvil Merthyr Tydfil"
    ],
    "gwent/newport": [
        "Newport, Wales",
        "Newport, Gwent, Wales",
        "Newport, Monmouthshire, Wales",
        "Newport, Monmouthshire, England",
        "Newport, Gwent",
        "Newport, Monmouthshire",
        "Newport, South Wales",
        "Newport-on-Usk"
    ],
    "gwent/cwmbran": [
        "Cwmbran, Wales",
        "Cwmbran Brewery",
        "Cwmbran New Town"
    ],
    "gwent/abergavenny": [
        "Abergavenny, Monmouthshire"
    ],
    "dyfed/carmarthen": [
        "Carmarthen, Wales",
        "Oaklands, Carmarthenshire",
        "Johnstown, Carmarthenshire"
    ],
    "dyfed/llanelli": [
        "Lakeside, Llanelli",
        "Llanelli, South Wales"
    ],
    "dyfed/haverfordwest": [
        "Haverfordwest, Wales",
        "Haverfordwest, Pembrokeshire"
    ],
    "dyfed/aberystwyth": [
        "Aberystwyth, Ceredigion",
        "Aberystwyth, Wales"
    ],
    "powys/newtown": [
        "Newtown, Powys",
        "Newtown, Montgomeryshire",
        "Newtown, Mongomeryshire",
        "Newtown, Wales",
        "Newtown, Powis"
    ],
    "powys/welshpool": [
        "Welshpoole"
    ],
    "powys/brecon": [
        "Brecknock",
        "Brecon, Wales",
        "Brecon Hgh School",
        "Brecon High School",
        "Llanfaes, Brecon"
    ],
    "gwynedd/bangor": [
        "Bangor, Gwynedd",
        "Bangor, Caernarfonshire",
        "Bangor, Wales",
        "Upper Bangor",
        "Bangor, Caernarvonshire"
    ],
    "gwynedd/caernarfon": [
        "Caernarfon Prison",
        "HMP Caernarfon",
        "HM Prison Caernarfon",
        "Caernarfon, Wales",
        "Caernarfon Food Festival",
        "Caernarfon, Gwynedd"
    ],
    "clwyd/wrexham": [
        "Wrexham, Wales",
        "Wrexham City Status",
        "People from wrexham",
        "Wrexham, Denbighshire",
        "Wrexham, Wrexham County Borough"
    ],
    "clwyd/rhyl": [
        "Y Rhyl",
        "Rhyl, Wales",
        "Rhyl, Denbighshire"
    ],
    "clwyd/llandudno": [
        "Llandudno, Wales",
        "Llandudno Urban District",
        "Llandudno Urban District Council"
    ],
    "lothian/edinburgh": [
        "Edinburgh, Scotland",
        "Edinburgh, United Kingdom",
        "Areas of edinburgh",
        "Old and New Towns of Edinburgh",
        "Inner Edinburgh",
        "Burgh of Edinburgh",
        "Suburbs of Edinburgh",
        "City of Edinburgh, Scotland"
    ],
    "lothian/livingston": [],
    "strathclyde/glasgow": [
        "Glasgow, Scotland",
        "West End of Glasgow",
        "The West End of Glasgow, Glasgow, United Kingdom",
        "Glasgow West End",
        "South East Glasgow",
        "North Glasgow",
        "Glasgow, United Kingdom",
        "East End, Glasgow"
    ],
    "strathclyde/paisley": [],
    "strathclyde/hamilton": [
        "Hamilton, South Lanarkshire",
        "Silvertonhill, Hamilton, Scotland",
        "Hamilton, Scotland",
        "High Earnock, Hamilton, Scotland",
        "Eddlewood, Hamilton, Scotland",
        "Laighstonehall, Hamilton, Scotland",
        "Meikle Earnock, Hamilton, Scotland",
        "Fairhill, Hamilton, Scotland"
    ],
    "strathclyde/east-kilbride": [
        "EK",
        "East Kilbride, Scotland",
        "Murrayhill, East Kilbride",
        "Town of East Kilbride",
        "East Kilbride, Lanarkshire",
        "College Milton, East Kilbride",
        "Gardenhall, East Kilbride"
    ],
    "strathclyde/greenock": [
        "Famous Greenockians",
        "Greenock, Scotland",
        "Greenock, Renfrewshire",
        "Greenock, Inverclyde",
        "Port of Greenock",
        "Greenock, UK",
        "Custom House, Greenock",
        "Custom House Quay, Greenock"
    ],
    "grampian/aberdeen": [
        "oil capital of Europe",
        "Aberdeen, Scotland",
        "Scotland Aberdeen",
        "Aberdeen Scotland",
        "City of Aberdeen council area",
        "Aberdeen City council area",
        "City of Aberdeen",
        "Aberdeen City"
    ],
    "grampian/elgin": [],
    "grampian/peterhead": [
        "Peterhead, Aberdeenshire",
        "Peterhead, Scotland",
        "Peterhead Town Trail",
        "The Peterhead Trail"
    ],
    "tayside/dundee": [
        "Dundee City",
        "Dundee, Scotland",
        "City of Dundee council area",
        "Dundee Central Library",
        "Dundee City council area",
        "City of Dundee, Scotland",
        "Dundee Port",
        "Dundee art"
    ],
    "tayside/perth": [
        "Perth, Australia",
        "Australia Perth",
        "Perth, W.A",
        "Perth WA",
        "Perth, WA",
        "Perth cultural history",
        "Perth, AU-WA",
        "Perth city centre"
    ],
    "fife/dunfermline": [
        "Dunfermline, Scotland",
        "City of Dunfermline",
        "Dunfermline, Fife",
        "Royal Burgh of Dunfermline",
        "Sheriff of Dunfermline"
    ],
    "fife/kirkcaldy": [
        "Lang Toun",
        "Kirkcaldy, Fife",
        "Kirkcaldy, Scotland"
    ],
    "fife/st-andrews": [
        "Royal Burgh of St Andrews",
        "St Andrews, Fife",
        "St Andrews Burgh Council",
        "St Andrews, Scotland",
        "St Andrews Citizen"
    ],
    "central-scotland/stirling": [
        "Stirling, Scotland",
        "Royal Burgh of Stirling",
        "Stirling burgh",
        "Riverside, Stirling",
        "Sports in Stirling",
        "Stirling, United Kingdom",
        "Stirling, Great Britain",
        "Stirling, UK"
    ],
    "central-scotland/falkirk": [
        "Falkirk, Scotland",
        "Falkirk, Stirlingshire"
    ],
    "borders/galashiels": [
        "Gala"
    ],
    "dumfries-and-galloway/dumfries": [
        "Queen of the South",
        "Town of Dumfries",
        "Dumfries, Scotland",
        "Provost of Dumfries",
        "Dumfries, Dumfries and Galloway"
    ],
    "highland/inverness": [
        "Inverness, Scotland",
        "City of Inverness",
        "Burgh of Inverness",
        "Inverness, Highland",
        "Town of Inverness",
        "Parliamentary burgh of Inverness"
    ],
    "highland/fort-william": [
        "Fort William, Scotland",
        "Fort William, Lochaber",
        "Fort William, Inverness-shire",
        "Burgh of Fort William",
        "Fort William, Highland"
    ],
    "antrim/belfast": [
        "Belfast, Ireland",
        "Belfast, United Kingdom",
        "Belfast, Northern Ireland",
        "City of Belfast, United Kingdom",
        "Belfast City",
        "City of Belfast",
        "St. Michael's Primary School, Belfast",
        "The weather in Belfast"
    ],
    "antrim/lisburn": [
        "Lisburn, Northern Ireland",
        "Lisburn telephone exchange code",
        "Lisburn STD Code",
        "Lisburn Area Code",
        "Lisburn, County Antrim",
        "Lisburn, Ireland",
        "Lisburne",
        "Lisburn Central Primary School"
    ],
    "antrim/ballymena": [
        "Ballymena, Northern Ireland",
        "Ballymena, County Antrim"
    ],
    "antrim/carrickfergus": [
        "Carrickfergus, Northern Ireland",
        "The Troubles in Carrickfergus",
        "Eden Primary School, Carrickfergus",
        "Carrickfergus, County Antrim"
    ],
    "down/newry": [
        "Newry City",
        "St John's Primary School, Newry",
        "St. John's Primary School, Newry",
        "Newry Urban District Council",
        "Newry, Northern Ireland",
        "Newry, County Down",
        "Newry, County Tyrone",
        "Newry, County Armagh"
    ],
    "down/bangor-ni": [
        "Bangor, County Down",
        "Bangor, Northern Ireland",
        "Bangor, Ireland",
        "Ashbury, Bangor",
        "Rathmore, Bangor",
        "Bangor, County Down, Ireland",
        "Bangor, co down",
        "Bangor Bay"
    ],
    "down/newtownards": [
        "Ards",
        "Newtownards, Co. Down"
    ],
    "down/downpatrick": [
        "The Troubles in Downpatrick"
    ],
    "armagh/armagh": [
        "Armagh City",
        "City of Armagh",
        "Armagh, County Armagh",
        "Christian Brothers Primary School Armagh",
        "Schools in Armagh City"
    ],
    "armagh/craigavon": [
        "Craigavon Urban Area",
        "The Troubles in Craigavon",
        "St. Anthony's Primary School, Craigavon",
        "Craigavon, County Armagh"
    ],
    "tyrone/omagh": [
        "Omagh, County Tyrone"
    ],
    "tyrone/dungannon": [
        "Dungannon Primary School"
    ],
    "tyrone/cookstown": [
        "St Joseph's Primary School, Cookstown",
        "The Troubles in Cookstown",
        "Cookstown, County Tyrone",
        "St. Joseph's Primary School, Cookstown"
    ],
    "fermanagh/enniskillen": [
        "The Diamond, Enniskillen",
        "Enniskillen, County Fermanagh",
        "Enniskillen, Fermanagh"
    ],
    "londonderry/derry": [
        "Derry",
        "Londonderry"
    ],
    "londonderry/coleraine": [
        "The Troubles in Coleraine",
        "Coleraine, County Londonderry"
    ],
    "londonderry/limavady": [
        "Newtown Limavady",
        "Newtonlimavady",
        "Newtownlimavady"
    ]
} as const;
